@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(owner, "Собственник / Жилец", "Использует мобильное приложение PropDevelopment для оплаты ЖКУ и управления доступом в дом")

System(mobile, "Мобильное приложение PropDevelopment", "Единый пользовательский интерфейс")

System_Boundary(prop, "PropDevelopment") {
  System(data_mgmt, "Контекст управления данными жильцов и объектов")
  System(integration, "Контекст взаимодействия с партнёрами")
}

System_Boundary(idp, "Система авторизации (Keycloak / AD)",  "Обеспечивает идентификацию и аутентификацию пользователей PropDevelopment")

System_Boundary(partner, "Партнёрская платформа 'Умный дом'", "Реализует функции интеллектуального домофона и шлагбаума, управляет оборудованием на объектах")

System_Boundary(access_points, "Физические точки двери/шлагбаумы",  "Домофоны и шлагбаумы, применяющие правила доступа, полученные от партнёрской платформы")

Rel(owner, mobile, "Пользуется", "Просмотр информации, управление доступами")
Rel(mobile, data_mgmt, "Запросы и команды по объектам и доступам", "REST API / мобильное подключение")
Rel(data_mgmt, integration, "Передаёт списки разрешённых пользователей, статусы, правила доступа", "События / REST")
Rel(integration, partner, "Отправляет данные о разрешениях, биометрию, номера, запросы на одноразовое открытие двери/шлагбаума", "REST API")
Rel(partner, integration, "Отправляет события проходов, отказов и тд", "Вебхуки / уведомления")
Rel(data_mgmt, idp, "Использует для авторизации пользователя", "OIDC/SAML")
Rel(partner, access_points, "Управляет оборудованием и применяет правила доступа")

@enduml
